### ISSUE TITLE
How to fix these version upgrade compile errors?

### ISSUE THREAD

**Issue by kenneth558** [Phoenix1747/Arduino-Pico-Analog-Correction#1]
I upgraded from previous version 1.2.x to latest PicoAnalogCorrection 1.3.0 in Arduino IDE v.2.0.3, which now produces these compile errors:

    <...my .ino file...> Compilation error: call of overloaded 'PicoAnalogCorrection(int)' is ambiguous
as the final error after having produced these errors:

    ...268:55: error: call of overloaded 'PicoAnalogCorrection(int)' is ambiguous  
    268 | PicoAnalogCorrection pico( ANALOG_INPUT_BITS_OF_BOARD );
    
    <...my .ino file...>265:/home/master/Arduino/libraries/PicoAnalogCorrection/PicoAnalogCorrection.h:     30:3: note: candidate: 'PicoAnalogCorrection::PicoAnalogCorrection(size_t, float, size_t, size_t)'
    30 |   PicoAnalogCorrection(size_t adc_res=12, float vref=3.3, size_t gnd_val=0, size_t vcc_val=0);
    
    /home/master/Arduino/libraries/PicoAnalogCorrection/PicoAnalogCorrection.h:29:3: note: candidate: 'PicoAnalogCorrection::PicoAnalogCorrection(size_t, size_t, size_t)'
    29 |   PicoAnalogCorrection(size_t adc_res=12, size_t gnd_val=0, size_t vcc_val=0);
     
    /home/master/Arduino/libraries/PicoAnalogCorrection/PicoAnalogCorrection.h:21:7: note: candidate: 'constexpr PicoAnalogCorrection::PicoAnalogCorrection(const PicoAnalogCorrection&)'
    21 | class PicoAnalogCorrection {
      |       ^~~~~~~~~~~~~~~~~~~~
    /home/master/Arduino/libraries/PicoAnalogCorrection/PicoAnalogCorrection.h:21:7: note: candidate: 'constexpr PicoAnalogCorrection::PicoAnalogCorrection(PicoAnalogCorrection&&)'

Thank you!

**Comment by NuclearPhoenixx** [comment]
Yes, thank you! I didn't test all the possible combinations of constructor parameters and completely missed that.
Should be fixed now with 1.3.1. 👍🏻 

Please bump this issue if it somehow still doesn't work for you.

**Comment by kenneth558** [comment]
👍🏻
